import Ript.Examples.CompositionalBitRealizations
import Ript.Semantics.ResourceChangingInterpretation

/-!
# Normal forms and semantic completeness for the common bit theory

The three-interface, two-generator syntax is the free category on a linear
graph.  This file proves a normalization theorem: every well-typed expression
is derivably equal to the unique path between its endpoints.  Consequently
the term model is thin, every heterogeneous interpretation reflects equality,
and the exact image of each reachable hom is the singleton generated by its
canonical path.
-/

set_option autoImplicit false

namespace Ript.Examples.CompositionalBitCompleteness

open CategoryTheory
open Ript.Core
open Ript.Examples.CompositionalBitRealizations
open Ript.Semantics
open Ript.Syntax

universe u v

/-! ## Canonical paths -/

/-- The six reachable paths in the free category on
`input → middle → output`. -/
inductive Canonical : Interface → Interface → Type where
  | inputId : Canonical .input .input
  | middleId : Canonical .middle .middle
  | outputId : Canonical .output .output
  | first : Canonical .input .middle
  | second : Canonical .middle .output
  | double : Canonical .input .output

namespace Canonical

/-- Reify a canonical path as a typed expression. -/
def toExpr : {X Y : Interface} → Canonical X Y → Expr signature X Y
  | _, _, .inputId => .id (signature := signature) Interface.input
  | _, _, .middleId => .id (signature := signature) Interface.middle
  | _, _, .outputId => .id (signature := signature) Interface.output
  | _, _, .first => .gen .firstFlip
  | _, _, .second => .gen .secondFlip
  | _, _, .double => .comp (.gen .firstFlip) (.gen .secondFlip)

/-- Composition of canonical paths. -/
def comp {X Y Z : Interface} :
    Canonical X Y → Canonical Y Z → Canonical X Z
  | .inputId, .inputId => .inputId
  | .inputId, .first => .first
  | .inputId, .double => .double
  | .middleId, .middleId => .middleId
  | .middleId, .second => .second
  | .outputId, .outputId => .outputId
  | .first, .middleId => .first
  | .first, .second => .double
  | .second, .outputId => .second
  | .double, .outputId => .double

/-- Syntactic composition derives to canonical-path composition. -/
theorem comp_derives {X Y Z : Interface}
    (left : Canonical X Y) (right : Canonical Y Z) :
    Derives (.comp left.toExpr right.toExpr) (left.comp right).toExpr := by
  cases left <;> cases right
  · simpa [toExpr, comp] using
      (Derives.id_comp (Expr.id (signature := signature) Interface.input))
  · simpa [toExpr, comp] using
      (Derives.id_comp (Expr.gen (signature := signature) Generator.firstFlip))
  · simpa [toExpr, comp] using
      (Derives.id_comp
        (Expr.comp (Expr.gen (signature := signature) Generator.firstFlip)
          (Expr.gen (signature := signature) Generator.secondFlip)))
  · simpa [toExpr, comp] using
      (Derives.id_comp (Expr.id (signature := signature) Interface.middle))
  · simpa [toExpr, comp] using
      (Derives.id_comp (Expr.gen (signature := signature) Generator.secondFlip))
  · simpa [toExpr, comp] using
      (Derives.id_comp (Expr.id (signature := signature) Interface.output))
  · simpa [toExpr, comp] using
      (Derives.comp_id (Expr.gen (signature := signature) Generator.firstFlip))
  · exact .refl _
  · simpa [toExpr, comp] using
      (Derives.comp_id (Expr.gen (signature := signature) Generator.secondFlip))
  · simpa [toExpr, comp] using
      (Derives.comp_id
        (Expr.comp (Expr.gen (signature := signature) Generator.firstFlip)
          (Expr.gen (signature := signature) Generator.secondFlip)))

/-- Canonical paths with fixed endpoints are unique. -/
theorem eq {X Y : Interface} (left right : Canonical X Y) : left = right := by
  cases left <;> cases right <;> rfl

/-- Fixed-endpoint canonical paths form a subsingleton. -/
instance {X Y : Interface} : Subsingleton (Canonical X Y) :=
  ⟨eq⟩

end Canonical

/-! ## Normalization and thinness -/

/-- Compute the unique canonical path represented by an expression. -/
def normalize {X Y : Interface} : Expr signature X Y → Canonical X Y
  | .gen .firstFlip => .first
  | .gen .secondFlip => .second
  | .id X => match X with
    | Interface.input => .inputId
    | Interface.middle => .middleId
    | Interface.output => .outputId
  | .comp left right => (normalize left).comp (normalize right)

/-- Every expression formally derives to its computed canonical path. -/
theorem normalize_derives {X Y : Interface} (expression : Expr signature X Y) :
    Derives expression (normalize expression).toExpr :=
  match expression with
  | .gen .firstFlip => .refl _
  | .gen .secondFlip => .refl _
  | .id Interface.input => .refl _
  | .id Interface.middle => .refl _
  | .id Interface.output => .refl _
  | .comp left right =>
      (Derives.comp_congr (normalize_derives left)
        (normalize_derives right)).trans
          (Canonical.comp_derives (normalize left) (normalize right))

/-- **Unique-path theorem.** Every two expressions with equal endpoints are
formally derivably equal. -/
theorem derives_unique {X Y : Interface}
    (left right : Expr signature X Y) : Derives left right := by
  have hright := normalize_derives right
  rw [show normalize right = normalize left from Subsingleton.elim _ _]
    at hright
  exact (normalize_derives left).trans hright.symm

/-- Every hom-set of the quotient term model is a subsingleton. -/
instance termModelHomSubsingleton
    (X Y : TermModel signature) : Subsingleton (X ⟶ Y) where
  allEq left right := by
    induction left using Quotient.inductionOn with
    | _ left =>
      induction right using Quotient.inductionOn with
      | _ right => exact Quotient.sound (derives_unique left right)

/-! ## Exact image and semantic completeness -/

/-- A semantic morphism lies in the image of a heterogeneous interpretation
when some common-syntax expression evaluates to it. -/
def InImage {S : Type} {C : Type u} [AddCommMonoid S] [PartialOrder S]
    [Category.{v} C] [HasProcessCost C S] {φ : Nat →+o S}
    (interpretation : ResourceChangingInterpretation.Interpretation
      (signature := signature) (C := C) φ)
    {X Y : Interface} (morphism : interpretation.obj X ⟶ interpretation.obj Y) :
    Prop :=
  ∃ expression : Expr signature X Y,
    ResourceChangingInterpretation.eval interpretation expression = morphism

/-- **Exact-image representation theorem.** For every reachable endpoint
pair, the semantic image is exactly the singleton containing the evaluation
of its canonical path. -/
theorem inImage_iff_eq_canonical
    {S : Type} {C : Type u} [AddCommMonoid S] [PartialOrder S]
    [Category.{v} C] [HasProcessCost C S] {φ : Nat →+o S}
    (interpretation : ResourceChangingInterpretation.Interpretation
      (signature := signature) (C := C) φ)
    {X Y : Interface} (canonical : Canonical X Y)
    (morphism : interpretation.obj X ⟶ interpretation.obj Y) :
    InImage interpretation morphism ↔
      morphism = ResourceChangingInterpretation.eval interpretation
        canonical.toExpr := by
  constructor
  · rintro ⟨expression, rfl⟩
    exact ResourceChangingInterpretation.soundness interpretation
      (derives_unique expression canonical.toExpr)
  · intro equality
    exact ⟨canonical.toExpr, equality.symm⟩

/-- Equality reflection for one heterogeneous interpretation. -/
def SemanticallyComplete
    {S : Type} {C : Type u} [AddCommMonoid S] [PartialOrder S]
    [Category.{v} C] [HasProcessCost C S] {φ : Nat →+o S}
    (interpretation : ResourceChangingInterpretation.Interpretation
      (signature := signature) (C := C) φ) : Prop :=
  ∀ {X Y : Interface} (left right : Expr signature X Y),
    ResourceChangingInterpretation.eval interpretation left =
      ResourceChangingInterpretation.eval interpretation right →
    Derives left right

/-- **Absolute semantic completeness for the linear common theory.** Every
heterogeneous model reflects equality because the typed syntax has one path
per reachable endpoint pair. -/
theorem semanticallyComplete
    {S : Type} {C : Type u} [AddCommMonoid S] [PartialOrder S]
    [Category.{v} C] [HasProcessCost C S] {φ : Nat →+o S}
    (interpretation : ResourceChangingInterpretation.Interpretation
      (signature := signature) (C := C) φ) :
    SemanticallyComplete interpretation := by
  intro X Y left right _
  exact derives_unique left right

/-- Reuse the abstract zero scalar cost of the quantum slice. -/
local instance quantumZeroCost :
    HasProcessCost Ript.Models.Quantum.Object Nat :=
  Ript.Examples.CommonBitRealizations.quantumZeroCost

/-- Reuse the abstract zero scalar cost of the thermal slice. -/
local instance thermalZeroCost :
    HasProcessCost Ript.Models.Thermal.ThermalObject Nat :=
  Ript.Examples.CommonBitRealizations.thermalZeroCost

/-- All six concrete interpretations reflect formal equality. -/
theorem sixModelSemanticCompleteness :
    SemanticallyComplete probabilityInterpretation ∧
    SemanticallyComplete quantumInterpretation ∧
    SemanticallyComplete causalInterpretation ∧
    SemanticallyComplete computationInterpretation ∧
    SemanticallyComplete semanticInterpretation ∧
    SemanticallyComplete thermalInterpretation := by
  exact ⟨semanticallyComplete _, semanticallyComplete _,
    semanticallyComplete _, semanticallyComplete _,
    semanticallyComplete _, semanticallyComplete _⟩

end Ript.Examples.CompositionalBitCompleteness
