import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum
import Ript.Models.Thermal.RationalGibbs

/-!
# Exact rational and irrational finite Gibbs spectra

This module exercises the rational Gibbs classification on three concrete
families:

* positive rational weights `2, 1` generate exact two-level probabilities
  `2/3, 1/3`;
* positive rational weights `1, 2, 3` generate exact three-level probabilities
  `1/6, 1/3, 1/2`;
* an independently specified two-level real spectrum with Boltzmann ratio
  `sqrt 2` cannot have exact rational Gibbs probabilities.

The positive-weight checks and resulting exact distributions are executable.
The irrational counterexample is a kernel proof using Mathlib's theorem that
`sqrt 2` is irrational.
-/

set_option autoImplicit false

namespace Ript.Examples.RationalGibbsSpectra

open Ript.Models.FiniteDistribution
open Ript.Models.FiniteStochastic
open Ript.Models.Thermal

noncomputable section

/-- Executable Boolean carrier for the two-level spectra. -/
abbrev twoLevelSystem : Object :=
  ⟨Bool, inferInstance, inferInstance⟩

/-- Positive rational Boltzmann weights producing probabilities `2/3, 1/3`. -/
def twoLevelWeights : twoLevelSystem → ℚ≥0 :=
  fun state : Bool ↦ if state then 1 else 2

/-- Both exact two-level weights are strictly positive. -/
theorem twoLevelWeights_pos (state : twoLevelSystem) :
    0 < twoLevelWeights state := by
  change Bool at state
  cases state <;> norm_num [twoLevelWeights]

/-- Exact executable equilibrium generated by the two rational weights. -/
def twoLevelEquilibrium : FinDist twoLevelSystem :=
  FiniteGibbsData.normalizedRationalWeights twoLevelWeights
    ⟨false⟩ twoLevelWeights_pos

/-- The low level has exact probability `2/3`. -/
theorem twoLevelEquilibrium_false :
    twoLevelEquilibrium.prob false = (2 : ℚ≥0) / 3 := by
  unfold twoLevelEquilibrium
  rw [FiniteGibbsData.normalizedRationalWeights_prob]
  change (2 : ℚ≥0) / (∑ state : Bool, if state then 1 else 2) = 2 / 3
  rw [Fintype.sum_bool]
  norm_num

/-- The high level has exact probability `1/3`. -/
theorem twoLevelEquilibrium_true :
    twoLevelEquilibrium.prob true = (1 : ℚ≥0) / 3 := by
  unfold twoLevelEquilibrium
  rw [FiniteGibbsData.normalizedRationalWeights_prob]
  change (1 : ℚ≥0) / (∑ state : Bool, if state then 1 else 2) = 1 / 3
  rw [Fintype.sum_bool]
  norm_num

/-- The corresponding logarithmic real spectrum at any positive inverse
temperature. -/
def twoLevelSpectrum (β : ℝ) (hβ : 0 < β) :
    FiniteGibbsData twoLevelSystem :=
  FiniteGibbsData.ofPositiveRationalWeights twoLevelWeights
    ⟨false⟩ twoLevelWeights_pos β hβ

/-- The analytic Gibbs probability of the low level is exactly the coercion
of `2/3`. -/
theorem twoLevelSpectrum_probability_false (β : ℝ) (hβ : 0 < β) :
    (twoLevelSpectrum β hβ).probability false = ((2 : ℚ≥0) / 3 : ℝ) := by
  unfold twoLevelSpectrum
  rw [FiniteGibbsData.ofPositiveRationalWeights_probability]
  exact_mod_cast twoLevelEquilibrium_false

/-- Executable three-level carrier. -/
abbrev threeLevelSystem : Object :=
  ⟨Fin 3, inferInstance, inferInstance⟩

/-- Positive rational Boltzmann weights `1, 2, 3`. -/
def threeLevelWeights : threeLevelSystem → ℚ≥0 :=
  fun level : Fin 3 ↦ (level.val + 1 : ℕ)

/-- Every exact three-level weight is strictly positive. -/
theorem threeLevelWeights_pos (level : threeLevelSystem) :
    0 < threeLevelWeights level := by
  change Fin 3 at level
  change 0 < ((level.val + 1 : ℕ) : ℚ≥0)
  exact Nat.cast_pos.mpr (Nat.succ_pos level.val)

/-- The exact three-level weights sum to six. -/
theorem threeLevelWeights_sum :
    ∑ level : threeLevelSystem, threeLevelWeights level = 6 := by
  change (∑ level : Fin 3, ((level.val + 1 : ℕ) : ℚ≥0)) = 6
  norm_num [threeLevelWeights, Fin.sum_univ_succ]

/-- Exact executable equilibrium generated by weights `1, 2, 3`. -/
def threeLevelEquilibrium : FinDist threeLevelSystem :=
  FiniteGibbsData.normalizedRationalWeights threeLevelWeights
    ⟨0⟩ threeLevelWeights_pos

/-- The first three-level mass is exactly `1/6`. -/
theorem threeLevelEquilibrium_zero :
    threeLevelEquilibrium.prob 0 = (1 : ℚ≥0) / 6 := by
  unfold threeLevelEquilibrium
  rw [FiniteGibbsData.normalizedRationalWeights_prob,
    threeLevelWeights_sum]
  norm_num [threeLevelWeights]

/-- The middle three-level mass is exactly `1/3`. -/
theorem threeLevelEquilibrium_one :
    threeLevelEquilibrium.prob 1 = (1 : ℚ≥0) / 3 := by
  unfold threeLevelEquilibrium
  rw [FiniteGibbsData.normalizedRationalWeights_prob,
    threeLevelWeights_sum]
  norm_num [threeLevelWeights]

/-- The last three-level mass is exactly `1/2`. -/
theorem threeLevelEquilibrium_two :
    threeLevelEquilibrium.prob 2 = (1 : ℚ≥0) / 2 := by
  unfold threeLevelEquilibrium
  rw [FiniteGibbsData.normalizedRationalWeights_prob,
    threeLevelWeights_sum]
  norm_num [threeLevelWeights]

/-- Logarithmic real spectrum generated by exact weights `1, 2, 3`. -/
def threeLevelSpectrum (β : ℝ) (hβ : 0 < β) :
    FiniteGibbsData threeLevelSystem :=
  FiniteGibbsData.ofPositiveRationalWeights threeLevelWeights
    ⟨0⟩ threeLevelWeights_pos β hβ

/-- The generated three-level spectrum satisfies the exact rationality side of
the general classification theorem. -/
theorem threeLevelSpectrum_hasRationalProbabilities (β : ℝ) (hβ : 0 < β) :
    (threeLevelSpectrum β hβ).HasRationalProbabilities :=
  FiniteGibbsData.ofPositiveRationalWeights_hasRationalProbabilities
    threeLevelWeights ⟨0⟩ threeLevelWeights_pos β hβ

/-- Independently specified two-level spectrum whose nontrivial Boltzmann
ratio is `sqrt 2`. -/
def irrationalTwoLevelSpectrum : FiniteGibbsData twoLevelSystem where
  energy := fun state : Bool ↦
    if state then -Real.log (Real.sqrt 2) else 0
  inverseTemperature := 1
  inverseTemperature_pos := by norm_num
  nonempty := ⟨false⟩

/-- The `sqrt 2` Boltzmann ratio cannot be represented by a nonnegative
rational, so this spectrum has no exact rational Gibbs distribution. -/
theorem irrationalTwoLevelSpectrum_not_hasRationalProbabilities :
    ¬irrationalTwoLevelSpectrum.HasRationalProbabilities := by
  intro hRational
  have hRatios :=
    (FiniteGibbsData.hasRationalProbabilities_iff_hasRationalBoltzmannRatiosAt
      irrationalTwoLevelSpectrum false).mp hRational
  rcases hRatios with ⟨ratios, _hratios_pos, hratios⟩
  have hsqrt_pos : 0 < Real.sqrt 2 := Real.sqrt_pos.2 (by norm_num)
  have hratio := hratios true
  change Real.exp (-(1 : ℝ) *
    ((-Real.log (Real.sqrt 2)) - 0)) = (ratios true : ℝ) at hratio
  rw [show -(1 : ℝ) * ((-Real.log (Real.sqrt 2)) - 0) =
      Real.log (Real.sqrt 2) by ring,
    Real.exp_log hsqrt_pos] at hratio
  exact irrational_sqrt_two ⟨(ratios true : ℚ), hratio.symm⟩

end

-- The rational-weight positivity certificates are decidable exact data.
#eval decide (∀ state : twoLevelSystem, 0 < twoLevelWeights state)

-- The two-level equilibrium is exactly `(2/3, 1/3)`.
#eval decide
  (twoLevelEquilibrium.prob false = (2 : ℚ≥0) / 3 ∧
    twoLevelEquilibrium.prob true = (1 : ℚ≥0) / 3)

-- The three-level equilibrium is exactly `(1/6, 1/3, 1/2)`.
#eval decide
  (threeLevelEquilibrium.prob 0 = (1 : ℚ≥0) / 6 ∧
    threeLevelEquilibrium.prob 1 = (1 : ℚ≥0) / 3 ∧
    threeLevelEquilibrium.prob 2 = (1 : ℚ≥0) / 2)

end Ript.Examples.RationalGibbsSpectra
