import Ript.Examples.UnivalentProcessUniverse
import Ript.Univalent.Completion

/-!
# Executable evidence for the truncated interface completion

The Boolean interface model exhibits the precise effect of object completion.
The externally distinct codes `bit ⊗ unit` and `unit ⊗ bit` become equal in the
completed object type because tensor symmetry supplies an internal identity.
The original code inequality is retained as a separate theorem, demonstrating
that completion equality does not leak back into raw Lean syntax.

The example also constructs a nontrivial identity-invariant numerical map.
`codeCardinality` assigns the exact finite cardinality generated by the Boolean
atom, sum, and tensor.  Every structural equivalence preserves it, so it
descends through `ObjectCompletion` and remains executable.
-/

set_option autoImplicit false

namespace Ript.Examples.UnivalentCompletion

open Ript.Univalent
open Ript.Examples.UnivalentProcessUniverse

/-- Exact cardinality of the finite interface denoted by a code in the Boolean
atom model. -/
def codeCardinality : Code Atom → Nat
  | .empty => 0
  | .unit => 1
  | .atom .bit => 2
  | .sum left right => codeCardinality left + codeCardinality right
  | .tensor left right => codeCardinality left * codeCardinality right

/-- Every generated structural equivalence preserves exact interface
cardinality. -/
theorem codeCardinality_equiv {A B : Code Atom} (equiv : EquivExpr A B) :
    codeCardinality A = codeCardinality B := by
  induction equiv with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ihFirst ihSecond => exact ihFirst.trans ihSecond
  | sumCongr _ _ ihLeft ihRight =>
      simp only [codeCardinality, ihLeft, ihRight]
  | tensorCongr _ _ ihLeft ihRight =>
      simp only [codeCardinality, ihLeft, ihRight]
  | sumSwap => simp only [codeCardinality, Nat.add_comm]
  | sumAssoc => simp only [codeCardinality, Nat.add_assoc]
  | sumUnitLeft => simp only [codeCardinality, Nat.zero_add]
  | sumUnitRight => simp only [codeCardinality, Nat.add_zero]
  | tensorSwap => simp only [codeCardinality, Nat.mul_comm]
  | tensorAssoc => simp only [codeCardinality, Nat.mul_assoc]
  | tensorUnitLeft => simp only [codeCardinality, Nat.one_mul]
  | tensorUnitRight => simp only [codeCardinality, Nat.mul_one]

/-- Exact code cardinality as an internal-identity-invariant map. -/
def cardinalityInvariant : model.InvariantMap Nat where
  toFun := codeCardinality
  respects path := by
    induction path using Quotient.inductionOn with
    | _ path => exact codeCardinality_equiv path.toEquivExpr

/-- Executable cardinality on the completed object type. -/
def completionCardinality : model.ObjectCompletion → Nat :=
  cardinalityInvariant.descend

#eval completionCardinality
  (UniverseModel.ObjectCompletion.ofCode model
    (.sum bitCode (.tensor bitCode bitCode)))

/-- Tensor-symmetric presentations become literally equal after object
completion. -/
theorem completedTensorPresentationsEqual :
    UniverseModel.ObjectCompletion.ofCode model bitTensorUnit =
      UniverseModel.ObjectCompletion.ofCode model unitTensorBit :=
  (UniverseModel.ObjectCompletion.ofCode_eq_iff_identity model _ _).2
    ⟨swapIdentity⟩

/-- Completion equality and raw-code inequality coexist: the quotient does not
retroactively identify the original Lean syntax trees. -/
theorem completionDoesNotReflectCodeEquality :
    UniverseModel.ObjectCompletion.ofCode model bitTensorUnit =
        UniverseModel.ObjectCompletion.ofCode model unitTensorBit ∧
      bitTensorUnit ≠ unitTensorBit :=
  ⟨completedTensorPresentationsEqual, bitTensorUnit_ne_unitTensorBit⟩

/-- The invariant inhabitedness predicate from Stage 11 descends to a
predicate on completed interface objects. -/
def completedInhabitedness : model.ObjectCompletion → Prop :=
  UniverseModel.InternalPredicate.descend model inhabitedPredicate

/-- The descended predicate agrees with the original internal predicate on
the tensor-symmetric Boolean presentation. -/
theorem completedInhabitedness_bitTensorUnit :
    completedInhabitedness
      (UniverseModel.ObjectCompletion.ofCode model bitTensorUnit) :=
  ⟨(false, PUnit.unit)⟩

end Ript.Examples.UnivalentCompletion
