import Mathlib.CategoryTheory.Category.Preorder
import Mathlib.CategoryTheory.Groupoid.FreeGroupoidOfCategory
import Ript.ForMathlib.CategoryTheory.Bicategory.Localization

/-!
# A walking arrow that genuinely acquires an inverse

This file isolates the smallest nontrivial localization step needed by the
higher Ript program.  The source is the walking-arrow category, represented by
the preorder `Fin 2`; its sole nonidentity arrow is not a bicategorical
equivalence in the associated locally discrete bicategory.  Mathlib's free
groupoid then adjoins a formal inverse.  Promoting the ordinary localization
functor to a pseudofunctor proves the full mark-inversion field of the compiled
bicategorical-localization interface and exposes the new inverse with both
inverse laws.

This is a genuine inverse-adjoining construction, not the still-open full
bicategorical localization of the resource-process bicategory.  The remaining
research obligation is to retain arbitrary noninvertible 2-cells and prove
biessential factorization plus local equivalence for that larger construction.
-/

set_option autoImplicit false
set_option linter.checkUnivs false

namespace Ript.Examples.WalkingLocalization

open CategoryTheory
open CategoryTheory.Bicategory

/-- The walking-arrow category: two ordered objects and one nonidentity
forward arrow. -/
abbrev Arrow := Fin 2

/-- The free groupoid generated by the walking-arrow category. -/
abbrev Completion := FreeGroupoid Arrow

/-- The unique nonidentity generating arrow of the walking-arrow category. -/
def arrow : (0 : Arrow) ⟶ (1 : Arrow) :=
  homOfLE (by decide)

/-- The canonical pseudofunctor that freely adds an inverse to the walking
arrow. -/
noncomputable abbrev inclusion :
    LocallyDiscrete Arrow ⥤ᵖ LocallyDiscrete Completion :=
  (FreeGroupoid.of Arrow).toPseudofunctor

/-- The underlying ordinary functor is Mathlib's free-groupoid localization
at all arrows. -/
theorem inclusionFunctor_isLocalization :
    Functor.IsLocalization (FreeGroupoid.of Arrow)
      (⊤ : CategoryTheory.MorphismProperty Arrow) :=
  inferInstance

@[simp]
theorem inclusion_map_arrow :
    inclusion.map arrow.toLoc = (FreeGroupoid.homMk arrow).toLoc :=
  rfl

/-- The formal inverse adjoined to the generating walking arrow. -/
noncomputable def inverse :
    LocallyDiscrete.mk (FreeGroupoid.mk (1 : Arrow)) ⟶
      LocallyDiscrete.mk (FreeGroupoid.mk (0 : Arrow)) :=
  (inv (FreeGroupoid.homMk arrow)).toLoc

/-- The generating arrow followed by its newly adjoined inverse is the
identity. -/
theorem inclusion_map_arrow_comp_inverse :
    inclusion.map arrow.toLoc ≫ inverse = 𝟙 _ := by
  rw [inclusion_map_arrow]
  apply Discrete.ext
  change FreeGroupoid.homMk arrow ≫ inv (FreeGroupoid.homMk arrow) = 𝟙 _
  simp

/-- The newly adjoined inverse followed by the generating arrow is the
identity. -/
theorem inverse_comp_inclusion_map_arrow :
    inverse ≫ inclusion.map arrow.toLoc = 𝟙 _ := by
  rw [inclusion_map_arrow]
  apply Discrete.ext
  change inv (FreeGroupoid.homMk arrow) ≫ FreeGroupoid.homMk arrow = 𝟙 _
  simp

/-- The walking-arrow inclusion inverts every source arrow. -/
theorem inclusion_inverts :
    (MorphismProperty.locallyDiscrete
      (⊤ : CategoryTheory.MorphismProperty Arrow)).IsInvertedBy inclusion :=
  MorphismProperty.locallyDiscrete_isInvertedBy
    (⊤ : CategoryTheory.MorphismProperty Arrow) (FreeGroupoid.of Arrow)
    (Localization.inverts (FreeGroupoid.of Arrow)
      (⊤ : CategoryTheory.MorphismProperty Arrow))

/-- The generating walking arrow is not an adjoint equivalence before the
free-groupoid localization. -/
theorem arrow_not_isEquivalence :
    ¬ IsEquivalence arrow.toLoc := by
  rintro ⟨⟨e, _⟩⟩
  have hInv : (1 : Arrow) ⟶ (0 : Arrow) := e.inv.as
  exact (by decide : ¬ (1 : Arrow) ≤ 0) hInv.le

/-- The image of the generating walking arrow is an adjoint equivalence after
free-groupoid localization. -/
theorem inclusion_map_arrow_isEquivalence :
    IsEquivalence (inclusion.map arrow.toLoc) :=
  inclusion_inverts arrow.toLoc trivial

/-- The walking-arrow construction is nontrivial: it inverts a marked arrow
that was not an equivalence in the source bicategory. -/
theorem inclusion_genuinely_adds_inverse :
    (¬ IsEquivalence arrow.toLoc) ∧
      IsEquivalence (inclusion.map arrow.toLoc) :=
  ⟨arrow_not_isEquivalence, inclusion_map_arrow_isEquivalence⟩

end Ript.Examples.WalkingLocalization
