import Mathlib.Logic.Equiv.Prod
import Mathlib.Logic.Equiv.Sum

/-!
# Deep syntax for an internally univalent process universe

This file defines syntax only.  `Code Atom` is a small universe of process
interfaces generated by atomic interfaces, the empty interface, the unit
interface, sums, and tensors.  `EquivExpr` is the syntax of structural
equivalences between codes.  `PathExpr` is a separate syntax of internal
identity witnesses with an explicit `ua` constructor from an internal
equivalence.

The distinction is deliberate: a `PathExpr A B` is not a Lean equality
`A = B`, and no constructor or theorem in this layer converts an arbitrary
Lean type equivalence into Lean type equality.
-/

set_option autoImplicit false

namespace Ript.Univalent

universe u

/-- Codes for a small universe of process interfaces.  Atomic interfaces are
closed under disjoint sum and parallel tensor. -/
inductive Code (Atom : Type u) : Type u where
  /-- The empty interface. -/
  | empty
  /-- The tensor unit interface. -/
  | unit
  /-- A user-supplied atomic interface. -/
  | atom (name : Atom)
  /-- A disjoint-choice interface. -/
  | sum (left right : Code Atom)
  /-- A parallel product interface. -/
  | tensor (left right : Code Atom)
  deriving DecidableEq, Repr

namespace Code

variable {Atom : Type u}

/-- Interpret interface codes as ordinary Lean types.  This is the external
set-level semantics of the deeply embedded universe. -/
def denote (atomSemantics : Atom → Type) : Code Atom → Type
  | .empty => Empty
  | .unit => PUnit
  | .atom name => atomSemantics name
  | .sum left right => Sum (denote atomSemantics left) (denote atomSemantics right)
  | .tensor left right => denote atomSemantics left × denote atomSemantics right

end Code

/-- Deep syntax for structural equivalences between interface codes.  These
constructors generate only the equivalences explicitly named by the internal
theory; they are data, not external equalities of codes. -/
inductive EquivExpr {Atom : Type u} : Code Atom → Code Atom → Type u where
  /-- Reflexive equivalence. -/
  | refl (A : Code Atom) : EquivExpr A A
  /-- Inverse equivalence. -/
  | symm {A B : Code Atom} (equiv : EquivExpr A B) : EquivExpr B A
  /-- Composition of internal equivalences. -/
  | trans {A B C : Code Atom} (first : EquivExpr A B)
      (second : EquivExpr B C) : EquivExpr A C
  /-- Sums preserve equivalence in both arguments. -/
  | sumCongr {A B C D : Code Atom} (left : EquivExpr A B)
      (right : EquivExpr C D) : EquivExpr (.sum A C) (.sum B D)
  /-- Tensors preserve equivalence in both arguments. -/
  | tensorCongr {A B C D : Code Atom} (left : EquivExpr A B)
      (right : EquivExpr C D) : EquivExpr (.tensor A C) (.tensor B D)
  /-- Symmetry of disjoint choice. -/
  | sumSwap (A B : Code Atom) : EquivExpr (.sum A B) (.sum B A)
  /-- Associativity of disjoint choice. -/
  | sumAssoc (A B C : Code Atom) :
      EquivExpr (.sum (.sum A B) C) (.sum A (.sum B C))
  /-- The empty interface is a left unit for disjoint choice. -/
  | sumUnitLeft (A : Code Atom) : EquivExpr (.sum .empty A) A
  /-- The empty interface is a right unit for disjoint choice. -/
  | sumUnitRight (A : Code Atom) : EquivExpr (.sum A .empty) A
  /-- Symmetry of parallel tensor. -/
  | tensorSwap (A B : Code Atom) : EquivExpr (.tensor A B) (.tensor B A)
  /-- Associativity of parallel tensor. -/
  | tensorAssoc (A B C : Code Atom) :
      EquivExpr (.tensor (.tensor A B) C) (.tensor A (.tensor B C))
  /-- The unit interface is a left tensor unit. -/
  | tensorUnitLeft (A : Code Atom) : EquivExpr (.tensor .unit A) A
  /-- The unit interface is a right tensor unit. -/
  | tensorUnitRight (A : Code Atom) : EquivExpr (.tensor A .unit) A

namespace EquivExpr

variable {Atom : Type u} {A B C : Code Atom}

/-- Interpret an internal equivalence expression as a Lean type equivalence.
The interpretation is one-way: it does not identify the source and target
codes in Lean. -/
def denote (atomSemantics : Atom → Type) :
    {A B : Code Atom} → EquivExpr A B →
      Code.denote atomSemantics A ≃ Code.denote atomSemantics B
  | _, _, .refl _ => Equiv.refl _
  | _, _, .symm equiv => (denote atomSemantics equiv).symm
  | _, _, .trans first second =>
      (denote atomSemantics first).trans (denote atomSemantics second)
  | _, _, .sumCongr left right =>
      Equiv.sumCongr (denote atomSemantics left) (denote atomSemantics right)
  | _, _, .tensorCongr left right =>
      Equiv.prodCongr (denote atomSemantics left) (denote atomSemantics right)
  | _, _, .sumSwap left right =>
      Equiv.sumComm (Code.denote atomSemantics left) (Code.denote atomSemantics right)
  | _, _, .sumAssoc left middle right =>
      Equiv.sumAssoc (Code.denote atomSemantics left)
        (Code.denote atomSemantics middle) (Code.denote atomSemantics right)
  | _, _, .sumUnitLeft code => Equiv.emptySum Empty (Code.denote atomSemantics code)
  | _, _, .sumUnitRight code => Equiv.sumEmpty (Code.denote atomSemantics code) Empty
  | _, _, .tensorSwap left right =>
      Equiv.prodComm (Code.denote atomSemantics left) (Code.denote atomSemantics right)
  | _, _, .tensorAssoc left middle right =>
      Equiv.prodAssoc (Code.denote atomSemantics left)
        (Code.denote atomSemantics middle) (Code.denote atomSemantics right)
  | _, _, .tensorUnitLeft code => Equiv.punitProd (Code.denote atomSemantics code)
  | _, _, .tensorUnitRight code => Equiv.prodPUnit (Code.denote atomSemantics code)

@[simp]
theorem denote_refl (atomSemantics : Atom → Type) (A : Code Atom) :
    denote atomSemantics (.refl A) = Equiv.refl (Code.denote atomSemantics A) :=
  rfl

@[simp]
theorem denote_symm (atomSemantics : Atom → Type) (equiv : EquivExpr A B) :
    denote atomSemantics (.symm equiv) = (denote atomSemantics equiv).symm :=
  rfl

@[simp]
theorem denote_trans (atomSemantics : Atom → Type) (first : EquivExpr A B)
    (second : EquivExpr B C) :
    denote atomSemantics (.trans first second) =
      (denote atomSemantics first).trans (denote atomSemantics second) :=
  rfl

end EquivExpr

/-- Deep syntax for internal identity witnesses.  `ua` is an introduction rule
from an equivalence expression into the internal identity type.  It does not
produce Lean equality. -/
inductive PathExpr {Atom : Type u} : Code Atom → Code Atom → Type u where
  /-- Reflexivity of internal identity. -/
  | refl (A : Code Atom) : PathExpr A A
  /-- Symmetry of internal identity. -/
  | symm {A B : Code Atom} (path : PathExpr A B) : PathExpr B A
  /-- Transitivity of internal identity. -/
  | trans {A B C : Code Atom} (first : PathExpr A B)
      (second : PathExpr B C) : PathExpr A C
  /-- Disjoint sums respect internal identity. -/
  | sumCongr {A B C D : Code Atom} (left : PathExpr A B)
      (right : PathExpr C D) : PathExpr (.sum A C) (.sum B D)
  /-- Parallel tensors respect internal identity. -/
  | tensorCongr {A B C D : Code Atom} (left : PathExpr A B)
      (right : PathExpr C D) : PathExpr (.tensor A C) (.tensor B D)
  /-- Internal univalence introduction for a structural equivalence. -/
  | ua {A B : Code Atom} (equiv : EquivExpr A B) : PathExpr A B

namespace PathExpr

variable {Atom : Type u} {A B C : Code Atom}

/-- Forget internal identity syntax to structural equivalence syntax. -/
def toEquivExpr : {A B : Code Atom} → PathExpr A B → EquivExpr A B
  | _, _, .refl code => .refl code
  | _, _, .symm path => .symm path.toEquivExpr
  | _, _, .trans first second => .trans first.toEquivExpr second.toEquivExpr
  | _, _, .sumCongr left right => .sumCongr left.toEquivExpr right.toEquivExpr
  | _, _, .tensorCongr left right => .tensorCongr left.toEquivExpr right.toEquivExpr
  | _, _, .ua equiv => equiv

/-- Interpret an internal identity expression in the external set-level model. -/
def denote (atomSemantics : Atom → Type) (path : PathExpr A B) :
    Code.denote atomSemantics A ≃ Code.denote atomSemantics B :=
  path.toEquivExpr.denote atomSemantics

@[simp]
theorem toEquivExpr_ua (equiv : EquivExpr A B) :
    (PathExpr.ua equiv).toEquivExpr = equiv :=
  rfl

@[simp]
theorem denote_ua (atomSemantics : Atom → Type) (equiv : EquivExpr A B) :
    (PathExpr.ua equiv).denote atomSemantics = equiv.denote atomSemantics :=
  rfl

@[simp]
theorem denote_refl (atomSemantics : Atom → Type) (A : Code Atom) :
    (PathExpr.refl A).denote atomSemantics =
      Equiv.refl (Code.denote atomSemantics A) :=
  rfl

@[simp]
theorem denote_symm (atomSemantics : Atom → Type) (path : PathExpr A B) :
    (PathExpr.symm path).denote atomSemantics =
      (path.denote atomSemantics).symm :=
  rfl

@[simp]
theorem denote_trans (atomSemantics : Atom → Type) (first : PathExpr A B)
    (second : PathExpr B C) :
    (PathExpr.trans first second).denote atomSemantics =
      (first.denote atomSemantics).trans (second.denote atomSemantics) :=
  rfl

end PathExpr

end Ript.Univalent
