import Mathlib.Order.Bounds.Basic
import Ript.Resource.ParallelBudget

/-!
# Cost functions and budget filtrations

This file proves the representation results relating two descriptions of
resource bounds on processes:

* a numerical cost on each morphism; and
* an increasing family of morphisms available at each budget.

Every lax additive process cost induces a sequential budget filtration.  If
the process category also has parallel costs, the induced filtration is
compatible with tensor.  Conversely, a filtration equipped with an attained
least admissible budget for every process determines a process cost.  This
explicit witness is the order-theoretic infimum, avoids nonconstructive choice,
and makes both representation round trips exact.
-/

set_option autoImplicit false

namespace Ript.Resource

open CategoryTheory
open MonoidalCategory
open Ript.Core

universe u v w

section CostFiltration

variable {C : Type u} [Category.{v} C]
variable {R : Type w} [AddCommMonoid R] [PartialOrder R] [ResourceAlgebra R]

/-- A sequential budget filtration records which morphisms are available at
each resource budget.  Availability is monotone in the budget, contains every
identity at budget zero, and is closed under additive serial composition. -/
structure HomFiltration (C : Type u) [Category.{v} C] (R : Type w)
    [AddCommMonoid R] [PartialOrder R] [ResourceAlgebra R] where
  /-- Membership of a process in a given budget layer. -/
  Mem : {X Y : C} → R → (X ⟶ Y) → Prop
  /-- Increasing the budget preserves availability. -/
  mono : ∀ {X Y : C} {r s : R} {f : X ⟶ Y}, Mem r f → r ≤ s → Mem s f
  /-- Every identity process is available at zero budget. -/
  id_mem : ∀ X : C, Mem 0 (𝟙 X)
  /-- Serial composition adds the advertised budgets. -/
  comp_mem : ∀ {X Y Z : C} {r s : R} {f : X ⟶ Y} {g : Y ⟶ Z},
    Mem r f → Mem s g → Mem (r + s) (f ≫ g)

namespace HomFiltration

variable (F : HomFiltration C R)

/-- The upper set of budgets at which a fixed process is available. -/
def budgets {X Y : C} (f : X ⟶ Y) : Set R :=
  {r | F.Mem r f}

/-- Optional compatibility of a sequential filtration with parallel tensor.
It is kept separate because tensor is not part of the common sequential
core. -/
def TensorCompatible [MonoidalCategory C] : Prop :=
  ∀ {X₁ Y₁ X₂ Y₂ : C} {r s : R} {f : X₁ ⟶ Y₁} {g : X₂ ⟶ Y₂},
    F.Mem r f → F.Mem s g → F.Mem (r + s) (f ⊗ₘ g)

end HomFiltration

/-- A budget filtration with an explicitly attained least budget for every
process.  The `minimum_mem` and `minimum_le` fields state exactly that this
budget is the infimum of the admissible upper set.  Keeping the witness as data
avoids selecting it with `Classical.choice`. -/
structure AttainedHomFiltration (C : Type u) [Category.{v} C] (R : Type w)
    [AddCommMonoid R] [PartialOrder R] [ResourceAlgebra R]
    extends HomFiltration C R where
  /-- The least admissible budget assigned to each process. -/
  minimum : {X Y : C} → (X ⟶ Y) → R
  /-- The assigned minimum is itself an admissible budget. -/
  minimum_mem : ∀ {X Y : C} (f : X ⟶ Y), Mem (minimum f) f
  /-- The assigned minimum is below every admissible budget. -/
  minimum_le : ∀ {X Y : C} (f : X ⟶ Y) {r : R}, Mem r f → minimum f ≤ r

namespace AttainedHomFiltration

variable (F : AttainedHomFiltration C R)

/-- The chosen budget is genuinely the least element of the admissible
budget set. -/
theorem minimum_isLeast {X Y : C} (f : X ⟶ Y) :
    IsLeast (F.toHomFiltration.budgets f) (F.minimum f) :=
  ⟨F.minimum_mem f, fun _ h ↦ F.minimum_le f h⟩

end AttainedHomFiltration

variable [HasProcessCost C R]

/-- Construct the nested budget filtration determined by a process-cost
function. -/
def costToFiltration : HomFiltration C R where
  Mem r f := processCost (R := R) f ≤ r
  mono hf hrs := hf.trans hrs
  id_mem X := by simp
  comp_mem := by
    intro X Y Z r s f g hf hg
    exact (processCost_comp f g).trans (add_le_add_resources hf hg)

/-- The filtration generated by a cost function carries an explicit attained
minimum equal to that original cost. -/
def costToAttainedFiltration : AttainedHomFiltration C R where
  toHomFiltration := costToFiltration (C := C) (R := R)
  minimum f := processCost (R := R) f
  minimum_mem _ := le_rfl
  minimum_le _ _ h := h

/-- Membership in the cost-induced filtration is exactly the advertised cost
inequality. -/
@[simp]
theorem costToFiltration_mem_iff {X Y : C} (r : R) (f : X ⟶ Y) :
    (costToFiltration (C := C) (R := R)).Mem r f ↔
      processCost (R := R) f ≤ r :=
  Iff.rfl

/-- The filtration induced by a cost function is increasing in its budget. -/
theorem costToFiltration_nested {X Y : C} {r s : R} {f : X ⟶ Y}
    (hf : (costToFiltration (C := C) (R := R)).Mem r f) (hrs : r ≤ s) :
    (costToFiltration (C := C) (R := R)).Mem s f :=
  hf.trans hrs

/-- The zero-budget layer of a cost-induced filtration contains every
identity. -/
theorem costToFiltration_id (X : C) :
    (costToFiltration (C := C) (R := R)).Mem 0 (𝟙 X) := by
  change processCost (R := R) (𝟙 X) ≤ 0
  rw [processCost_id]

/-- Cost-induced filtration layers compose with additive budgets. -/
theorem costToFiltration_comp {X Y Z : C} {r s : R}
    {f : X ⟶ Y} {g : Y ⟶ Z}
    (hf : (costToFiltration (C := C) (R := R)).Mem r f)
    (hg : (costToFiltration (C := C) (R := R)).Mem s g) :
    (costToFiltration (C := C) (R := R)).Mem (r + s) (f ≫ g) :=
  (costToFiltration (C := C) (R := R)).comp_mem hf hg

section Parallel

variable [MonoidalCategory C] [HasParallelProcessCost C R]

/-- A filtration induced by a parallel process cost is tensor-compatible. -/
theorem costToFiltration_tensorCompatible :
    (costToFiltration (C := C) (R := R)).TensorCompatible := by
  intro X₁ Y₁ X₂ Y₂ r s f g hf hg
  exact (processCost_tensor f g).trans (add_le_add_resources hf hg)

/-- Cost-induced filtration layers tensor with additive budgets. -/
theorem costToFiltration_tensor {X₁ Y₁ X₂ Y₂ : C} {r s : R}
    {f : X₁ ⟶ Y₁} {g : X₂ ⟶ Y₂}
    (hf : (costToFiltration (C := C) (R := R)).Mem r f)
    (hg : (costToFiltration (C := C) (R := R)).Mem s g) :
    (costToFiltration (C := C) (R := R)).Mem (r + s) (f ⊗ₘ g) :=
  costToFiltration_tensorCompatible hf hg

end Parallel

end CostFiltration

section Reconstruction

variable {C : Type u} [Category.{v} C]
variable {R : Type w} [AddCommMonoid R] [PartialOrder R] [ResourceAlgebra R]
variable (F : AttainedHomFiltration C R)

/-- Recover the process cost as the attained infimum of its admissible
filtration budgets. -/
def filtrationToCost {X Y : C} (f : X ⟶ Y) : R :=
  F.minimum f

/-- Taking the least budget of a cost-induced filtration recovers the
original process cost exactly. -/
@[simp]
theorem costToFiltration_toCost [HasProcessCost C R] {X Y : C} (f : X ⟶ Y) :
    filtrationToCost (costToAttainedFiltration (C := C) (R := R)) f =
      processCost (R := R) f :=
  rfl

/-- The recovered cost satisfies the infimum universal property for the
admissible budget set. -/
theorem filtrationToCost_isLeast {X Y : C} (f : X ⟶ Y) :
    IsLeast (F.toHomFiltration.budgets f) (filtrationToCost F f) :=
  F.minimum_isLeast f

/-- Reconstructing budget layers from an attained infimum cost agrees
pointwise with the original filtration. -/
theorem filtrationToCost_toFiltration_of_attained
    {X Y : C} (r : R) (f : X ⟶ Y) :
    filtrationToCost F f ≤ r ↔ F.Mem r f :=
  ⟨fun h ↦ F.mono (F.minimum_mem f) h, fun h ↦ F.minimum_le f h⟩

/-- Every process belongs to the filtration layer indexed by its recovered
cost. -/
theorem filtrationToCost_mem {X Y : C} (f : X ⟶ Y) :
    F.Mem (filtrationToCost F f) f :=
  F.minimum_mem f

/-- Recovered costs are subadditive under serial composition. -/
theorem filtrationToCost_comp {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z) :
    filtrationToCost F (f ≫ g) ≤ filtrationToCost F f + filtrationToCost F g :=
  F.minimum_le (f ≫ g) (F.comp_mem (F.minimum_mem f) (F.minimum_mem g))

section WithZero

variable [OrderBot R]

/-- If zero is the least resource, the recovered cost of every identity is
exactly zero. -/
theorem filtrationToCost_id (hzero : (⊥ : R) = 0) (X : C) :
    filtrationToCost F (𝟙 X) = 0 := by
  apply le_antisymm
  · exact F.minimum_le (𝟙 X) (F.id_mem X)
  · rw [← hzero]
    exact bot_le

/-- An attained filtration with zero as the least resource canonically
determines a valid lax additive process-cost structure. -/
@[instance_reducible]
def filtrationToProcessCost (hzero : (⊥ : R) = 0) : HasProcessCost C R where
  cost f := filtrationToCost F f
  cost_id X := filtrationToCost_id F hzero X
  cost_comp f g := filtrationToCost_comp F f g

end WithZero

section ParallelReconstruction

variable [MonoidalCategory C]

/-- A tensor-compatible attained filtration reconstructs a cost that is
subadditive under parallel composition. -/
theorem filtrationToCost_tensor
    (hTensor : F.toHomFiltration.TensorCompatible)
    {X₁ Y₁ X₂ Y₂ : C} (f : X₁ ⟶ Y₁) (g : X₂ ⟶ Y₂) :
    filtrationToCost F (f ⊗ₘ g) ≤ filtrationToCost F f + filtrationToCost F g :=
  F.minimum_le (f ⊗ₘ g) (hTensor (F.minimum_mem f) (F.minimum_mem g))

end ParallelReconstruction

end Reconstruction

end Ript.Resource
