import Ript.Syntax.Cost

/-!
# Sequential equational derivations

`Derives` is the explicit congruence generated by the category laws. It is
kept separate from semantic equality so that soundness and relative
completeness have non-circular statements.
-/

set_option autoImplicit false

namespace Ript.Syntax

universe u w

/-- Formal equality derivations for sequential process expressions. -/
inductive Derives {R : Type w} {signature : Signature.{u, w} R} :
    {X Y : signature.Obj} → Expr signature X Y → Expr signature X Y → Prop where
  /-- Every expression derives itself. -/
  | refl {X Y : signature.Obj} (f : Expr signature X Y) : Derives f f
  /-- Derivability is symmetric. -/
  | symm {X Y : signature.Obj} {f g : Expr signature X Y} :
      Derives f g → Derives g f
  /-- Derivability is transitive. -/
  | trans {X Y : signature.Obj} {f g h : Expr signature X Y} :
      Derives f g → Derives g h → Derives f h
  /-- Composition respects derivability in both arguments. -/
  | comp_congr {X Y Z : signature.Obj}
      {f f' : Expr signature X Y} {g g' : Expr signature Y Z} :
      Derives f f' → Derives g g' →
        Derives (.comp f g) (.comp f' g')
  /-- The identity is a left unit for composition. -/
  | id_comp {X Y : signature.Obj} (f : Expr signature X Y) :
      Derives (.comp (.id X) f) f
  /-- The identity is a right unit for composition. -/
  | comp_id {X Y : signature.Obj} (f : Expr signature X Y) :
      Derives (.comp f (.id Y)) f
  /-- Sequential composition is associative. -/
  | assoc {W X Y Z : signature.Obj} (f : Expr signature W X)
      (g : Expr signature X Y) (h : Expr signature Y Z) :
      Derives (.comp (.comp f g) h) (.comp f (.comp g h))

/-- The setoid of expressions modulo formal category-law derivations. -/
def derivesSetoid {R : Type w} (signature : Signature.{u, w} R)
    (X Y : signature.Obj) : Setoid (Expr signature X Y) where
  r := Derives
  iseqv := ⟨Derives.refl, Derives.symm, Derives.trans⟩

namespace Derives

variable {R : Type w} [AddMonoid R]
variable {signature : Signature.{u, w} R} {X Y : signature.Obj}
variable {f g : Expr signature X Y}

/-- Formal category-law derivations preserve the computed syntax cost. -/
theorem syntaxCost_eq (derivation : Derives f g) :
    f.syntaxCost = g.syntaxCost := by
  induction derivation with
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | comp_congr _ _ ih₁ ih₂ => exact congrArg₂ (· + ·) ih₁ ih₂
  | id_comp _ => simp
  | comp_id _ => simp
  | assoc _ _ _ => simp [add_assoc]

end Derives

end Ript.Syntax
