import Mathlib.Algebra.Order.Hom.Monoid
import Mathlib.CategoryTheory.Monoidal.Free.Basic

/-!
# Signatures for monoidal process syntax

Object expressions are free monoidal trees over primitive wire types. A
computable flattening maps every tree to its finite-list normal form; keeping
the tree during elaboration makes associators and unitors well-typed without
casts and lets semantic interpretations target arbitrary monoidal categories.
-/

set_option autoImplicit false

namespace Ript.Syntax

open CategoryTheory MonoidalCategory

universe u w

/-- Typed primitive processes whose interfaces are free monoidal object trees. -/
structure MonoidalSignature (R : Type w) where
  /-- Primitive wire types. -/
  Wire : Type u
  /-- Primitive process symbols indexed by input and output object trees. -/
  Gen : FreeMonoidalCategory Wire → FreeMonoidalCategory Wire → Type u
  /-- Declared cost of each primitive process. -/
  cost : {X Y : FreeMonoidalCategory Wire} → Gen X Y → R

namespace MonoidalSignature

/-- The object language generated by tensor, unit, and primitive wires. -/
abbrev Obj {R : Type w} (signature : MonoidalSignature.{u, w} R) :=
  FreeMonoidalCategory signature.Wire

/-- Flatten a free monoidal object tree to its finite-list normal form. -/
def normalForm {R : Type w} {signature : MonoidalSignature.{u, w} R} :
    signature.Obj → List signature.Wire
  | .of wire => [wire]
  | .unit => []
  | .tensor X Y => normalForm X ++ normalForm Y

/-- A primitive wire normalizes to a singleton list. -/
@[simp]
theorem normalForm_of {R : Type w} {signature : MonoidalSignature.{u, w} R}
    (wire : signature.Wire) : normalForm (.of wire) = [wire] :=
  rfl

/-- The tensor unit normalizes to the empty list. -/
@[simp]
theorem normalForm_unit {R : Type w} {signature : MonoidalSignature.{u, w} R} :
    normalForm (signature := signature) (𝟙_ (FreeMonoidalCategory signature.Wire)) = [] :=
  rfl

/-- Tensor normalizes by concatenating the component normal forms. -/
@[simp]
theorem normalForm_tensor {R : Type w} {signature : MonoidalSignature.{u, w} R}
    (X Y : signature.Obj) :
    normalForm (X ⊗ Y) = normalForm X ++ normalForm Y :=
  rfl

/-- Push the declared generator costs of a signature along an ordered
additive resource translation.  Wires and process generators are unchanged,
so this operation changes resource accounting without changing the executable
process language. -/
def mapCost {R S : Type w} [AddCommMonoid R] [Preorder R]
    [AddCommMonoid S] [Preorder S] (signature : MonoidalSignature.{u, w} R)
    (φ : R →+o S) : MonoidalSignature.{u, w} S where
  Wire := signature.Wire
  Gen := signature.Gen
  cost g := φ (signature.cost g)

/-- Cost translation acts pointwise on primitive generators. -/
@[simp]
theorem mapCost_cost {R S : Type w} [AddCommMonoid R] [Preorder R]
    [AddCommMonoid S] [Preorder S] (signature : MonoidalSignature.{u, w} R)
    (φ : R →+o S) {X Y : (signature.mapCost φ).Obj}
    (g : (signature.mapCost φ).Gen X Y) :
    (signature.mapCost φ).cost g = φ (signature.cost g) :=
  rfl

/-- Successive resource translations compose definitionally on signatures. -/
@[simp]
theorem mapCost_comp {R S T : Type w}
    [AddCommMonoid R] [Preorder R] [AddCommMonoid S] [Preorder S]
    [AddCommMonoid T] [Preorder T] (signature : MonoidalSignature.{u, w} R)
    (φ : R →+o S) (ψ : S →+o T) :
    (signature.mapCost φ).mapCost ψ = signature.mapCost (ψ.comp φ) :=
  rfl

end MonoidalSignature

end Ript.Syntax
